version: "3.9"

services:
  app:
    build:
        context: .
        args:
          - DEV=true
    ports:
        - "8000:8000"
    volumes:
        - ./app:/app
    command:
       sh -c "python manage.py wait_for_db &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=bhmhmhkjaov1novqtcqy-postgresql.services.clever-cloud.com
      - DB_NAME=bhmhmhkjaov1novqtcqy
      - DB_USER=uc4srroswls0mhbz7hlr
      - DB_PASSWORD=mHR90aHmROam1IltfhW3
      - DB_PORT=5432

