---
name: ci

on: push

jobs:
  test-lint:
    name: Test and lint
    runs-on: ubuntu-lastest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOCKEN }}
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run : docker-compose run --rm app sh -c "flake8"